#!/usr/bin/zsh

system_pkg_version_lazygit(){
	local pkg=$1
	local vtype=$2

	if [[ $vtype = installed ]]; then
		lazygit --version 2>/dev/null |
			sed -e 's/, /\n/g' |
			grep '^version=' |
			sed -e 's/version=//'

	else
		local url="https://api.github.com/repos/jesseduffield/lazygit"

		url="${url}/releases/latest"

		curl -s $url |
			grep '"tag_name":' |
			sed -E 's/.*"v*([^"]+)".*/\1/'

	fi | pkg_version_normalize
}

system_pkg_doinstall_lazygit(){
	local version=$(system_pkg_version_lazygit lazygit repo)

	url="https://github.com/jesseduffield/lazygit/releases/latest/download"
	url="${url}/lazygit_${version}_Linux_x86_64.tar.gz"

	sudo_init || return 1

	local cwd=$(pwd)
	cd /usr/local/bin

	curl -Lo - $url |
	sudo tar zxf - lazygit

	local retval=$?

	cd $cwd
	return $retval
}
