#!/usr/bin/zsh

NEOVIM_DOWNLOAD_URL="https://github.com/neovim/neovim/releases/latest/download"
NEOVIM_DOWNLOAD_DIR=""

system_pkg_install_neovim_app(){
	zpackage system install libfuse2 || return 1

	NEOVIM_DOWNLOAD_DIR=$(mktemp -d)

	zpackage system install neovim || return 1
}

system_pkg_register_neovim_app(){
 	system_pkg_register_app nvim vi  N
 	system_pkg_register_app nvim vim Y

	echo
}


system_pkg_doinstall_neovim(){
	local package=$1

	######################################################################
	# We are installing "app.image" download from "github".
	# If "neovim" has been isntalled as debian packge we
	# have to uninstall it first. We will call "zpackage"
	# "uninstall" function, which will check for presence
	# of package, and remove it if present.
	#
	zpackage system uninstall neovim

	system_pkg_download_neovim

	local src_prog=$NEOVIM_DOWNLOAD_DIR/nvim.appimage
	local dst_prog=/usr/local/bin/nvim.appimage
	local dst_link=/usr/local/bin/nvim

	local mode='oug+rx'

	sudo_cmd cp $src_prog $dst_prog || return 1
	sudo_cmd chmod $mode $dst_prog  || return 1

	[[ -L $dst_link ]] || sudo_cmd ln -s $dst_prog $dst_link || return 1

	echo '"neovim" installed!'

 # 	system_pkg_register_neovim nvim vi  N
 # 	system_pkg_register_neovim nvim vim Y
	#
	# echo
}

system_pkg_version_neovim(){
	local pkg=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		nvim --version 2>/dev/null |
			grep '^NVIM' |
			awk '{
				gsub(/^[^0-9]+/,"",$2)
				print  $2
			}'

	else
		system_pkg_download_neovim || return 

		local prog=$NEOVIM_DOWNLOAD_DIR/nvim.appimage

		$prog --version 2>/dev/null |
			grep '^NVIM' |
			awk '{
				gsub(/^[^0-9]+/,"",$2)
				print  $2
			}'

	fi | awk -F. '{
				major = $1
				minor = $2 * 100 + $3

				printf "%d.%d", major, minor
			}'
}

system_pkg_download_neovim(){
	local prog=$NEOVIM_DOWNLOAD_DIR/nvim.appimage

	[[ -f $prog ]] && return

	local url="$NEOVIM_DOWNLOAD_URL/nvim.appimage"
	local mode='oug+rx'

	curl -sfL -o $prog $url 2>/dev/null || return 1
	chmod $mode $prog

	return 0
}

system_pkg_postinstall_neovim(){
	system_pkg_clean_neovim
}

system_pkg_clean_neovim(){
	[[ -z $NEOVIM_DOWNLOAD_DIR ]] && return
	[[ -d $NEOVIM_DOWNLOAD_DIR ]] || return

	rm -rf $NEOVIM_DOWNLOAD_DIR

	unset NEOVIM_DOWNLOAD_DIR
}

