#!/usr/bin/zsh

SCRIPT_DIR=${0:a:h}

SCRIPT_DEBUG=0
GLOBAL_INSTALL=0

source $SCRIPT_DIR/lib/core


#############################################
# main functions
#
exec_help(){
	cat <<-EOF

		   ${y}usage:${n}
		      install COMMAND

		   ${y}commands:${n}
		      neovim     - install latest neovim
		      register   - register neovim in "alternatives""
		      packages   - install other programs/modules (nodejs, ruby,
		                   perl, pynvim, ruby nvim, rust, ...)
					clipboard  - install/select new clipboard tool if
					             one already installed

		      all        - run all the above in single run

		   ${y}note:${n}
		      command names can be abbrevated: neo, cli, ...

	EOF

	exit
}

exec_all(){
	install_packages
	install_neovim
}

exec_neovim(){
	install_neovim
}

exec_register(){
	register_neovim
}

exec_packages(){
	install_packages
}

exec_clipboard(){
	CLIPOARD_KEEEP_EXISTING=0

	zpackage system install clipboard-app
}


#############################################
# package installation functions
#
install_neovim(){
		zpackage system install  neovim-app
		zpackage system register neovim-app
}

register_neovim(){
		zpackage system register neovim-app
}

install_packages(){
	zpackage system packages-select

	local core=(core ${SELECTED_MODULES[(i)system]})
	
	local MODULES=($core ${(o)${(@k)SELECTED_MODULES}:|core})

	local module

	for module in $MODULES; do
		zpackage $module install ${=MODULE_PACKAGES[$module]}
	done

	download_installer
}

download_installer(){
	zpackage system install nvim-installer
}


##############################################################################
# Show some notifications on end of install
#
parse_arguments(){

	############################################################
	# parse command options 
	#
	#   --global -q    - install all modulees as global ones
	#   --debug  -d    - show some debugging output
	#
	local ARGS

	zparseopts -E -D -A ARGS \
		g d -global -debug

	[[ ${+ARGS[-g]}       -eq 1 ]] && GLOBAL_INSTALL=1
	[[ ${+ARGS[--global]} -eq 1 ]] && GLOBAL_INSTALL=1
	[[ ${+ARGS[-d]}       -eq 1 ]] && SCRIPT_DEBUG=1
	[[ ${+ARGS[--debug]}  -eq 1 ]] && SCRIPT_DEBUG=1

	local commands=(all neovim packages register clipboard)
	local cmd=(${(M)commands:#${1}*})

	[[ $#cmd -eq 0 ]] && SCRIPT_COMMAND="exec_help"
	[[ $#cmd -eq 1 ]] && SCRIPT_COMMAND="exec_$cmd"
	[[ $#cmd -gt 1 ]] && SCRIPT_COMMAND="exec_help"

	shift 2>/dev/null

	SCRIPT_ARGS=("$@")
}

# system_pkg_version_nvim_installer nvim-installer installed
# system_pkg_version_nvim_installer nvim-installer repo
# check_if_root

parse_arguments $@

$SCRIPT_COMMAND "${SCRIPT_ARGS[@]}"

pkg_notifications_show
