#!/usr/bin/zsh

__LUA_HOME=$__NVIM_BRICKS/lua


#############################################
# GARBAGE
#
lua_pkg_install_ORG(){
	local pkg=$1

	install_luarocks

	if [[ $__LUA_SETUP -eq 0 ]]; then
		count_action fail lua $pkg "luarocks not installed"
		return 1
	fi

	alert_msg "Checking [lua]" "$pkg"

	local local_version=$(
		luarocks --lua-version 5.1 --tree $__LUA_HOME list $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(installed\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1
	)

	local repo_version=$(
		luarocks search $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(src\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1
	)

	clear_screen 4

	if [[ $local_version = $repo_version ]]; then
		count_action success lua $pkg kept
		return
	fi

	if [[ -z $local_version ]]; then
		alert_msg "Installing [luarocks]" "$pkg"
		count_action $? lua $pkg install
	else
		alert_msg "Upgrading [luarocks]" "$pkg"
		count_action $? lua $pkg upgrade
	fi

	echo
	local errors=$(
		luarocks --lua-version 5.1 --tree ${__LUA_HOME} install $pkg 3>&1 1>&2 2>&3
	)

	echo

	if [[ -n $errors ]]; then
		echo "${y}Errors:${n}"
		echo $errors | sed -e "s/^/${s}   /"
		echo ${n}
	fi
}


#############################################
# lua packages functions
#
lua_pkg_setup(){
	[[ ${+__LUA_SETUP} -eq 1 ]] && return $__LUA_SETUP

	__LUA_SETUP=0
	zpackage system install lua || __LUA_SETUP=1

	return $__LUA_SETUP
}

lua_pkg_version(){
	local pkg=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		luarocks --lua-version 5.1 --tree $__LUA_HOME list $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(installed\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1

	else
		luarocks search $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(src\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1

	fi

}

lua_pkg_doinstall(){
	local pkg=$1

	echo
	local errors=$(
		luarocks --lua-version 5.1 --tree ${__LUA_HOME} install $pkg 3>&1 1>&2 2>&3
	)

	echo

	if [[ -n $errors ]]; then
		echo "${y}Errors:${n}"
		echo $errors | sed -e "s/^/${s}   /"
		echo ${n}
	fi
}


#############################################
# MISSING
#
lua_pkg_check_MISSING(){
}

lua_pkg_uninstall_MISSING(){
}

