#!/usr/bin/zsh

__LUA_HOME=$__NVIM_BRICKS/lua


#############################################
# lua packages functions
#
lua_pkg_setup(){
	[[ ${+__LUA_SETUP} -eq 1 ]] && return $__LUA_SETUP

	__LUA_SETUP=1

	pkg_create_modules_dir || return 1
	zpackage system install lua-module || return 1

	__LUA_SETUP=0

	return 0
}

lua_pkg_version(){
	local pkg=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		luarocks --lua-version 5.1 --tree $__LUA_HOME list $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(installed\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1

	else
		luarocks search $pkg |
		awk -v pkg="${(L)pkg}" '
			/^$/{found = 0}
			found && /\(src\)/{print $1}
			tolower($0) == pkg { found = 1}
		' |
		sort -V |
		tail -1

	fi | pkg_version_normalize

}

lua_pkg_doinstall(){
	local pkg=$1

	echo
	local errors=$(
		luarocks --lua-version 5.1 --tree ${__LUA_HOME} install $pkg 3>&1 1>&2 2>&3
	)

	echo

	if [[ -n $errors ]]; then
		echo "${y}Errors:${n}"
		echo $errors | sed -e "s/^/${s}   /"
		echo ${n}
	fi
}


#############################################
# MISSING
#
lua_pkg_check_MISSING(){
}

lua_pkg_uninstall_MISSING(){
}

