#!/usr/bin/zsh

__NODE_HOME=$__NVIM_BRICKS/node


#############################################
# node packages functions
#
node_pkg_setup(){
	[[ ${+__NODE_SETUP} -eq 1 ]] && return $__NODE_SETUP

	__NODE_SETUP=1

	pkg_create_modules_dir || return 1
	zpackage system install nodejs-module || return 1

	export npm_config_prefix=$__NODE_HOME

	__NODE_SETUP=0
	zpackage node install npm
	__NODE_SETUP=$?

	return $__NODE_SETUP
}

node_pkg_version(){
	local package=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		npm list -g --depth 0 2>/dev/null |
			grep " ${package}@" |
			sed -e "s/.* ${package}@//"

	else
		npm view ${package} version 2>/dev/null

	fi
}

node_pkg_doinstall(){
	local package=$1

	npm install -g $package
}


#############################################
# MISSING
#
node_pkg_check_MISSING(){
}

node_pkg_uninstall_MISSING(){
}

