#!/usr/bin/zsh

__PERL_HOME=$__NVIM_BRICKS/perl5
__PERL_LIB=$__PERL_HOME/lib/perl5


#############################################
# GARBAGE
#
perl_pkg_install_ORG(){
	local package=$1

	install_perl

	if [[ $__PERL_SETUP -eq 0 ]]; then
		count_action fail perl $package "perl not installed"
		return 1
	fi

	alert_msg "Checking [perl]" "$package"

	local has_perl5=$([[ -d ~/perl5 ]] && echo "YES")
	local has_pkg=$(perl -I $__PERL_LIB -e "use $package" 2>&1)

	if [[ -n $has_pkg ]]; then
		clear_screen 4

		alert_msg "Installing [perl]" "$package"

		echo
		cpanm --local-lib=$__PERL_HOME -n $package

		count_action $? perl $package install
		echo
	else
		local tar_pkg=${package//::/-}
		local local_version=$(perl -I $__PERL_LIB -M${package} -e 'print $'${package}'::VERSION . "\n";')
		local repo_version=$(cpanm --info $package | grep "/${tar_pkg}.*tar.gz" | sed -e "s:.*/${tar_pkg}-::" -e 's:\.tar\.gz$::')

		clear_screen 4

		if [[ $local_version != $repo_version ]]; then
			alert_msg "Upgrading [perl]" "$package"

			echo
			cpanm --local-lib=$__PERL_HOME -n $package

			count_action $? perl $package upgrade
			echo
		else
			count_action success perl $package kept
		fi
	fi

	# if "perl5" directory has been created
	# delete it
	#
	[[ -z $has_perl5 ]] && [[ -d ~/perl5 ]] && rm -rf ~/perl5
}


#############################################
# node packages functions
#
perl_pkg_setup(){
	[[ ${+__PERL_SETUP} -eq 1 ]] && return $__PERL_SETUP

	__PERL_SETUP=1

	pkg_create_modules_dir || return 1
	zpackage system install perl-module || return 1

	local system_pkg=(${@:#*::*})
	local perl_pkg=(${(M)@:#*::*})

	__PERL_SETUP=0

	zpackage perl install App::cpanminus $perl_pkg

	__PERL_SETUP=$?

	return $__PERL_SETUP
}

perl_pkg_version(){
	local package=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		local tar_pkg=${package//::/-}

		perl -I $__PERL_LIB -M${package} -e 'print $'${package}'::VERSION . "\n";'

	else
		cpanm --info $package |
			grep "/${tar_pkg}.*tar.gz" |
			sed -e "s:.*/${tar_pkg}-::" -e 's:\.tar\.gz$::'
	fi

}

perl_pkg_doinstall(){
	local package=$1

	local has_perl5=$([[ -d ~/perl5 ]] && echo "YES")
	local has_pkg=$(perl -I $__PERL_LIB -e "use $package" 2>&1)

	cpanm --local-lib=$__PERL_HOME -n $package

	# if "perl5" directory has been created
	# delete it
	#
	[[ -z $has_perl5 ]] && [[ -d ~/perl5 ]] && rm -rf ~/perl5
}



#############################################
# MISSING
#
perl_pkg_check_MISSING(){
}

perl_pkg_uninstall_MISSING(){
}

