#!/usr/bin/zsh

__RUBY_HOME=$__NVIM_BRICKS/ruby
__RUBY_BIN=$__RUBY_HOME/bin


#############################################
# ruby packages functions
#
ruby_pkg_setup(){
	[[ ${+__RUBY_SETUP} -eq 1 ]] && return $__RUBY_SETUP

	__RUBY_SETUP=1

	pkg_create_modules_dir || return 1
	pkg_create_ruby_dir    || return 1

	zpackage system install ruby-module || return 1

	__RUBY_SETUP=0

	return 0
}

ruby_pkg_version(){
	local package=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		gem info $package |
			grep "^$package " |
			sed -e "s/^${package} (//" -e 's/)//'

	else
		gem info $package --remote |
			grep "^$package " |
			sed -e "s/^${package} (//" -e 's/)//'

	fi

}

ruby_pkg_doinstall(){
	local package=$1

	gem install --user-install -n $__RUBY_BIN $package
	return $?
}

