#!/usr/bin/zsh

__CARGO_INDEX=0
__CARGO_HOME=$__NVIM_BRICKS/cargo
__RUSTUP_HOME=$__NVIM_BRICKS/rustup

__CARGO_BIN=$__CARGO_HOME/bin


#############################################
# rust module functions
#
rust_pkg_setup(){
	[[ ${+__RUST_SETUP} -eq 1 ]] && return $__RUST_SETUP

	__RUST_SETUP=1

	export PATH=$__CARGO_BIN:$PATH
	export CARGO_HOME=$__CARGO_HOME
	export RUSTUP_HOME=$__RUSTUP_HOME

	# echo "PATH-XX:$PATH"

	pkg_create_modules_dir || return 1
	zpackage system install rust-module || return 1

	__RUST_SETUP=0

	return 0
}

system_pkg_install_rust_module(){

	zpackage system install make rust

	return $?
}

system_pkg_version_rust(){
	local pkg=$1
	local vtype=$2
	local installed=0
	local rustup=$(which rustup)
	local rversion="0.0"

	[[ $rustup = $__CARGO_BIN/rustup ]] && installed=1

	if [[ $installed -eq 1 ]]; then
		rversion=$(
			rustup -V 2>/dev/null |
			awk '/^rustup /{print $2}' |
			pkg_version_normalize
		)
	fi

	if [[ $vtype = installed ]]; then
		echo $rversion
	else
		if [[ $installed -eq 1 ]]; then
			local need_update=$(rustup check | grep -v "Up to date")

			[[ -n $need_update ]] && rversion="99.0"
		else
			rversion="99.0"
		fi

		echo $rversion
	fi
}

system_pkg_doinstall_rust(){
	local rustup=$(which rustup)

	echo "IN DOINSTALL RUST"

	if [[ $rustup = $__CARGO_BIN/rustup ]]; then
		rustup update
		return 0
	else
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
			sh -s -- -y --no-modify-path
		return $?
	fi
}


#############################################
# rust packages functions
#
rust_pkg_version(){
	local package=$1
	local vtype=$2

	if [[ $vtype = "installed" ]]; then
		cargo install --list 2>/dev/null |
			grep "^${package##*::} " |
			awk '{print $NF}' |
			sed -e 's/:$//' -e 's/^v//'
	
	else
		if [[ __CARGO_INDEX -eq 0 ]]; then
			(
				cd $CARGO_HOME
				cargo update --dry-run 1>&2 2>/dev/null
			)

			__CARGO_INDEX=1
		fi

		cargo search -q ${package##*::} 2>/dev/null |
			grep "^${package##*::} = " |
			sed -e 's/^.*= "//' -e 's/".*//'
		
	fi | pkg_version_normalize
}

rust_pkg_doinstall(){
	local package=$1

	cargo install ${package##*::}

	# warning: be sure to add `/home/koske/.local/share/nvim/cargo/bin` to your PATH to be able to run the installed binaries
}

