#!/usr/bin/zsh

__SYSTEM_STATE=$__NVIM_SHARE/.state

typeset -gA SYSTEM_SNAPSHOT


#############################################
# GARBAGE
#
system_pkg_install_ORG(){
	local pkg=$1
	local todo

	zpackage system setup || return 1

	system_package action $pkg todo
	# echo "TODO:$todo $pkg"

	if [[ $todo = keep ]] then
		count_action success system $pkg kept
		return 0
	elif [[ $todo = missing ]] then
		count_action fail system $pkg missing
		return 1
	elif [[ ${todo%%:*} = old ]] then
		local parts=${(s.:.)todo}
		count_action fail system $pkg "$parts[2] $parts[3]"
		return 1
	fi

	pkg=${todo#*:}

	alert_msg "Installing [$OS]" "${pkg}"

	echo
	zpackage system preinstall $pkg
	zpackage system doinstall $pkg
	local result=$?
	count_action $result system $pkg install
	zpackage system postinstall $pkg

	return $result
}

install_system_pkg_ORG (){
	local todo
	local package=$1

	sys_package $package action todo

	if [[ $todo = keep ]] then
		count_action success system $package kept
		return 0
	elif [[ $todo = missing ]] then
		count_action fail system $package missing
		return 1
	elif [[ ${todo%%:*} = old ]] then
		local parts=${(s.:.)todo}
		count_action fail system $package "$parts[2] $parts[3]"
		return 1
	fi

	package=${todo#*:}

	alert_msg "Installing [$OS]" "${package}"

	echo
	sys_package $package install

	count_action $? system $package install

	return $?
}

system_pkg_action_ORG(){
		local __package=${1%/*}
		local __version=${${${(M)1:#*/*}##*/}:-0.0}
		local __store=$2
		local __action

		if [[ -n $PROVIDES_PATTERN[$__package] ]]; then
			system_pkg_action_multy  __action $1
		else
			system_pkg_action_single __action $1
		fi

		eval "$__store=$__action"
}

system_pkg_action_single_ORG(){
	local action
	local store=$1; shift
	local package=${1%/*}
	local version=${${${(M)1:#*/*}##*/}:-0.0}

	alert_msg "Checking [$OS]" "${package}"
	echo

	local inst_version=$(system_package version $package installed)
	local repo_version=$(system_package version $package repo)
	local inst_version_n=$(normalize_version $inst_version)
	local repo_version_n=$(normalize_version $repo_version)
	local need_version=${(j:.:)${(@s:.:)version}[1,2]}

	echo "Installed: $inst_version"
	echo "Repo:      $repo_version"
	echo "Short:     $repo_version_n"
	echo "Need:      $need_version"

	if [[ -z inst_version ]]; then
		if [[ -z $repo_version ]]; then
			action=missing
		elif ! is_newer $repo_version_n $need_version; then
			action=old:$repo_version_n:$need_version
		else
			action=install:$package
		fi

	else
		if [[ -z $repo_version ]]; then
			action=keep
		elif [[ $inst_version = $repo_version ]]; then
			action=keep
		elif ! is_newer $repo_version_n $inst_version_n; then
			action=keep
		else
			action=install:$package
		fi

	fi

	eval "$store=$action"

	clear_screen 9
}

system_pkg_action_multy_ORG(){
	local action
	local store=$1; shift
	local package=${1%/*}
	local version=${${${(M)1:#*/*}##*/}:-0.00}
	local need_version=${(j:.:)${(@s:.:)version}[1,2]}
	local repo_packages=()
	local inst_packages=()
	local -A valid_packages
	local -A invalid_packages
	local -A valid_installed
	local -A invalid_installed
	local pkg pkg_name pkg_version nrm_version

	alert_msg "Checking [$OS]" "$package"

	system_package $package provides repo_packages

	# echo REPO PACKAGES: ${(qq)repo_packages}

	# check for already installed packages, their versions
	# and if they fulfill minimal version criteria
	#
	for pkg in $repo_packages; do
		pkg_name=${pkg%%;*}
		pkg_version=$(system_package $pkg_name version installed)
		nrm_version=$(normalize_version $pkg_version)

		# echo PN:$pkg_name
		# echo IV:$pkg_version
		# echo NV:$nrm_version

		if [[ -n $pkg_version ]]; then
			inst_packages+=("$pkg_name;$pkg_version;$nrm_version")

			if [[ $need_version -gt 0 ]]; then
				# if [[ $nrm_version -ge $need_version ]]; then
				if is_newer $nrm_version $need_version; then
					valid_installed[$pkg_name]=1
				else
					invalid_installed[$pkg_name]=1
				fi

			else
				valid_installed[$pkg_name]=1
			fi
		fi
	done

	# echo "need: $need_version"
	#
	# echo INV: ${(k)invalid_installed}
	# echo VAL: ${(k)valid_installed}
	# echo "-------------------"

	if [[ -n $inst_packages ]]; then
		echo
		echo "${y}Installed packages:${n}"
		echo "${n}${(l:80::-:)void}"

		for pkg in $inst_packages; do
			pkg_name=${pkg%%;*}
			nrm_version=${pkg##*;}

			if [[ -n $invalid_installed[$pkg_name] ]]; then
				## validity="${y}(required min is ${need_version})${n}"
				validity="${n}!! ${y}(< ${need_version})${n}"
			else
				validity="${n}OK"
			fi

			printf "%s%-20s %s%6s      %s\n" ${b} ${pkg_name} ${c} ${nrm_version} $validity
		done
	fi

	# for each repo package check if it is valid version
	#
	for pkg in $repo_packages; do
		pkg_name=${pkg%%;*}
		nrm_version=${pkg##*;}

		if [[ $need_version -gt 0 ]]; then
			if is_newer $nrm_version $need_version; then
				valid_packages[$pkg_name]=1
			else
				invalid_packages[$pkg_name]=1
			fi

		else
			valid_packages[$pkg_name]=1
		fi
	done

	# echo INV: ${(k)invalid_packages}
	# echo VAL: ${(k)valid_packages}
	# echo "-------------------"

	local validity parts void

	# echo INST: ${(qq)inst_packages}

	if [[ -n $repo_packages ]]; then
		echo
		echo "${y}Available packages:${n}"
		echo "${n}${(l:80::-:)void}"

		for pkg in $repo_packages; do
			pkg_name=${pkg%%;*}
			nrm_version=${pkg##*;}

			if [[ -n $invalid_packages[$pkg_name] ]]; then
				validity="${n}!! ${y}(< ${need_version})${n}"
			else
				validity="${n}OK"
			fi

			printf "%s%-20s %s%6s      %s\n" ${b} ${pkg_name} ${c} ${nrm_version} $validity
			echo -n ${n}
		done
	fi

	# check for
	# check if installed version are valid
	echo
}


#############################################
# system packages functions
#
system_pkg_setup(){
	[[ ${+__SYSTEM_SETUP} -eq 1 ]] && return $__SYSTEM_SETUP

	__SYSTEM_SETUP=0

	pkg_create_local_dir
	system_pkg_upgrade || __SYSTEM_SETUP=1

	return $__SYSTEM_SETUP
}

system_pkg_check(){
	local pkg=$1

	local version=$(system_package version $pkg installed)

	[[ -z $version ]] && return 1

	return 0
}

system_pkg_preinstall(){
	SYSTEM_SNAPSHOT[pre]=$(zpackage system snapshot)
}

system_pkg_postinstall(){
	local pre_snapshot=(${=SYSTEM_SNAPSHOT[pre]})
	local post_snapshot=($(zpackage system snapshot))
	local added_packages=(${post_snapshot:|pre_snapshot})

	####################################
	# save list of added packages
	#
	[[ -f $__SYSTEM_STATE ]] || touch $__SYSTEM_STATE

	local -U new_state=($(cat $__SYSTEM_STATE; echo $added_packages))

	echo ${(o)new_state} > $__SYSTEM_STATE
}

