#!/usr/bin/zsh

__SYSTEM_STATE=$__NVIM_SHARE/.state

typeset -gA SYSTEM_SNAPSHOT

__CORE_PACKAGES=(unzip tar gzip wget curl git)


#############################################
# system packages functions
#
system_pkg_setup(){
	[[ ${+__SYSTEM_SETUP} -eq 1 ]] && return $__SYSTEM_SETUP

	__SYSTEM_SETUP=1

	pkg_create_local_dir || return 1
	system_pkg_upgrade   || return 1

	__SYSTEM_SETUP=0

	return 0
}

system_pkg_check(){
	local pkg=$1

	local version=$(system_package version $pkg installed)

	[[ -z $version ]] && return 1

	return 0
}

system_pkg_preinstall(){
	SYSTEM_SNAPSHOT[pre]=$(zpackage system snapshot)
}

system_pkg_postinstall(){
	local pre_snapshot=(${=SYSTEM_SNAPSHOT[pre]})
	local post_snapshot=($(zpackage system snapshot))
	local added_packages=(${post_snapshot:|pre_snapshot})

	####################################
	# save list of added packages
	#
	[[ -f $__SYSTEM_STATE ]] || touch $__SYSTEM_STATE

	local -U new_state=($(cat $__SYSTEM_STATE; echo $added_packages))

	echo ${(o)new_state} > $__SYSTEM_STATE
}

